# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'explorer.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(941, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 33))
        self.widget.setObjectName("widget")
        self.exploreBtn = QtWidgets.QPushButton(self.widget)
        self.exploreBtn.setGeometry(QtCore.QRect(10, 0, 97, 27))
        self.exploreBtn.setObjectName("exploreBtn")
        self.StepBtn = QtWidgets.QPushButton(self.widget)
        self.StepBtn.setGeometry(QtCore.QRect(120, 0, 97, 27))
        self.StepBtn.setObjectName("StepBtn")
        self.stepBox = QtWidgets.QSpinBox(self.widget)
        self.stepBox.setGeometry(QtCore.QRect(230, 0, 48, 27))
        self.stepBox.setMinimum(1)
        self.stepBox.setMaximum(100000)
        self.stepBox.setObjectName("stepBox")
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.widget1 = QtWidgets.QWidget(self.splitter_2)
        self.widget1.setObjectName("widget1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.pathsView = QtWidgets.QTreeView(self.widget1)
        self.pathsView.setObjectName("pathsView")
        self.gridLayout.addWidget(self.pathsView, 1, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.widget2 = QtWidgets.QWidget(self.splitter)
        self.widget2.setObjectName("widget2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.disasmBrowser = QtWidgets.QTextBrowser(self.widget2)
        self.disasmBrowser.setObjectName("disasmBrowser")
        self.gridLayout_2.addWidget(self.disasmBrowser, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.regsTab = QtWidgets.QWidget()
        self.regsTab.setObjectName("regsTab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.regsTab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.regsBrowser = QtWidgets.QTextBrowser(self.regsTab)
        self.regsBrowser.setObjectName("regsBrowser")
        self.gridLayout_6.addWidget(self.regsBrowser, 0, 0, 1, 1)
        self.tabWidget.addTab(self.regsTab, "")
        self.memTab = QtWidgets.QWidget()
        self.memTab.setObjectName("memTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.memTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.memTab)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.addrBox = QtWidgets.QLineEdit(self.memTab)
        self.addrBox.setObjectName("addrBox")
        self.gridLayout_4.addWidget(self.addrBox, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.memBrowser = QtWidgets.QTextBrowser(self.memTab)
        self.memBrowser.setObjectName("memBrowser")
        self.gridLayout_5.addWidget(self.memBrowser, 1, 0, 1, 1)
        self.tabWidget.addTab(self.memTab, "")
        self.gridLayout_3.addWidget(self.splitter_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exploreBtn.setText(_translate("MainWindow", "Explore"))
        self.StepBtn.setText(_translate("MainWindow", "Step"))
        self.label_2.setText(_translate("MainWindow", "Paths"))
        self.label_3.setText(_translate("MainWindow", "Status"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.regsTab), _translate("MainWindow", "Registers"))
        self.label.setText(_translate("MainWindow", "Address:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.memTab), _translate("MainWindow", "Memory"))

